name: linux autotools clang

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      id: install_dependencies
      run: sudo apt-get update -qq && sudo apt-get -y install libboost-all-dev libopenal-dev libmad0-dev libvorbis-dev libfaad-dev qtbase5-dev libqt5gui5 libqt5multimedia5 qtmultimedia5-dev libqt5multimediawidgets5 libgl-dev libglu-dev

    - name: Set clang as the compiler to use
      id: set_clang
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Configure
      id: configure
      run: ( ./autogen.sh && ./configure ) || ( cat config.log; exit 1 )

    - name: Compile
      id: compile
      run: make -j4

    - name: Build and run unit tests
      id: run_unit_tests
      run: make -j4 check
