name: macos autotools clang

on:
  [push, pull_request]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      id: install_dependencies
      run: brew install automake boost qt5 openal-soft faad2

    - name: Set clang as the compiler to use
      id: set_clang
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/usr/local/opt/qt5/lib/pkgconfig" >> $GITHUB_ENV

    - name: Configure
      id: configure
      run: ( ./autogen.sh && ./configure ) || ( cat config.log; exit 1 )

    - name: Compile
      id: compile
      run: make -j4

    - name: Build and run unit tests
      id: run_unit_tests
      run: make -j4 check
